### ISSUE TITLE
Getting spawns from santa monica

### ISSUE THREAD

**Issue by johan-eriksson** [leandroxk/pokemon-alert#5]
Not sure if this is an issue with your program or FPM, but occasionally I will get results from santa monica instead of my designated place, which usually results in me getting 10 mails at a time since they get a lot of spawns over there.

**Comment by thaiminh8xpro** [comment]
Seems like waryas just add a redirection for impeding being scrapped and we return to the orginal page instead of the location-page

**Comment by leandroxk** [comment]
Fixed
